# Generated by Django 5.0.14 on 2025-10-17 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
